VIA_ENABLE = no
EXTRAKEY_ENABLE = yes # Audio control and System control
MOUSEKEY_ENABLE = yes
AUTO_SHIFT_ENABLE = no
DYNAMIC_MACRO_ENABLE = yes
COMMAND_ENABLE = no
LEADER_ENABLE = no
TAP_DANCE_ENABLE = no

SECRETS_ENABLED = no
MACROS_ENABLED = no
CAPSWORD_ENABLED = yes

DEBUG_ENABLE = no
KEYLOGGER_ENABLE = no
UCIS_ENABLE = no
AUTOLOG_ENABLE = no
LTO_ENABLE = yes
CONSOLE_ENABLE = no
VERBOSE = no
DEBUG_MATRIX_SCAN_RATE  = no
DEBUG_MATRIX = no
MAGIC_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
