EXTRAKEY_ENABLE = yes # Audio control and System control
MOUSEKEY_ENABLE = yes
CAPS_WORD_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
MAGIC_ENABLE = yes
LTO_ENABLE = yes

DEBOUNCE_TYPE = sym_eager_pk

# RGBLIGHT_ENABLE = no
# RGB_MATRIX_ENABLE = yes

VERBOSE = no
DEBUG_MATRIX_SCAN_RATE  = no
DEBUG_MATRIX = no
