EXTRAKEY_ENABLE = yes # Audio control and System control
MOUSEKEY_ENABLE = yes
AUTO_SHIFT_ENABLE = no
DYNAMIC_MACRO_ENABLE = no
COMMAND_ENABLE = no
LEADER_ENABLE = no
TAP_DANCE_ENABLE = yes
MAGIC_ENABLE = yes
COMBO_ENABLE = no
CAPS_WORD_ENABLE = yes

# DEBOUNCE_TYPE = sym_defer_g
DEBOUNCE_TYPE = sym_eager_pk

SECRETS_ENABLED = no
MACROS_ENABLED = no
#CAPSWORD_ENABLED = no

BOOTMAGIC_ENABLE = no
WPM_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
OLED_ENABLE = yes
OLED_DRIVER = ssd1306
ENCODER_ENABLE = yes
WAIT_FOR_USB = yes

ENABLE_NKRO = yes

BOOTLOADER = atmel-dfu

DEBUG_ENABLE = no
KEYLOGGER_ENABLE = no
UCIS_ENABLE = no
AUTOLOG_ENABLE = no
LTO_ENABLE = yes
CONSOLE_ENABLE = no
VERBOSE = no
DEBUG_MATRIX_SCAN_RATE  = no
DEBUG_MATRIX = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no

ifeq ($(strip $(OLED_ENABLE)), yes)
	SRC += oled.c
endif
