#pragma once

#include QMK_KEYBOARD_H
#include "pmjpmj.h"

enum Layers {
    L_BASE_COLEMAK_DH_HRM, L_BASE_COLEMAK_DH, L_BASE_QWERTY_HRM, L_BASE_QWERTY, L_BASE_GAME, L_LOWER, L_RAISE, L_ADJUST, L_ONESHOT
};
