EXTRAKEY_ENABLE = yes # Audio control and System control
MOUSEKEY_ENABLE = no
AUTO_SHIFT_ENABLE = yes
MACROS_ENABLED = yes
DYNAMIC_MACRO_ENABLE = yes
COMMAND_ENABLE = no
LEADER_ENABLE = no
TAP_DANCE_ENABLE = no

BOOTMAGIC_ENABLE = no
WPM_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = SSD1306

DEBUG_ENABLE = no
KEYLOGGER_ENABLE = no
UCIS_ENABLE = no
AUTOLOG_ENABLE = no
LTO_ENABLE = yes
CONSOLE_ENABLE = no
VERBOSE = no
DEBUG_MATRIX_SCAN_RATE  = no
DEBUG_MATRIX = no
MAGIC_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
